GET http://127.0.0.1:1234/users/
Accept: application/json

###

GET http://127.0.0.1:1234/users/6
Accept: application/json

###

POST http://127.0.0.1:1234/users/
Accept: application/json
Content-Type: application/json

{
  "name": "Mira Slavna",
  "age": 31
}

###

PUT http://127.0.0.1:1234/users/6
Accept: application/json
Content-Type: application/json

{
  "id": 6,
  "name": "------",
  "age": 0
}

###

PATCH http://127.0.0.1:1234/users/6
Accept: application/json
Content-Type: application/json

{
  "name": "Misha Loki"
}

###

DELETE http://127.0.0.1:1234/users/6

GET http://127.0.0.1:1234/books/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImV4cCI6MTYzNTYwODU3N30.i04Wv3HSRhZEc4Pl8KxMHAz00XRBfRCJnBeXNeRg2do

##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################
###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################

GET http://127.0.0.1:1234/books/1
Accept: application/json

###

POST http://127.0.0.1:1234/books/
Accept: application/json
Content-Type: application/json

{
  "name": "graph monte cristo",
  "author": "duma",
  "year": 1500,
  "height": 1
}

###

POST http://127.0.0.1:1234/books/1/take?owner=Oleg
Accept: application/json

###

POST http://127.0.0.1:1234/books/1/return
Accept: application/json

###


PUT http://127.0.0.1:1234/books/1
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "name": "Mira Slavna",
  "email": "93784@mail.com",
  "password": "34908672408985",
  "age": 45
}

###

PATCH http://127.0.0.1:1234/books/1
Accept: application/json
Content-Type: application/json

{
  "name": "Misha Loki"
}

###

DELETE http://127.0.0.1:1234/books/1